# This is an example configuration file
# To learn more, see the full config.yaml reference: https://docs.continue.dev/reference

name: Example Config
version: 1.0.0
schema: v1

# Define which models can be used
# https://docs.continue.dev/customization/models
models:
  - "title": "gemini-3.1-pro-preview"
    "provider": "openai"
    "model": "gemini-3.1-pro-preview"
    "apiKey": "sk-ipx7p17GMOnlO7e2ku4tXjYHu6fAfu5CB6wPq8ukU4jPnc7e"
    "apiBase": "https://api.gptoai.top/"

# MCP Servers that Continue can access
# https://docs.continue.dev/customization/mcp-tools
mcpServers:
  - uses: anthropic/memory-mcp
